In [4]:
import numpy as np


# In[3]:


#dir(np)


# In[5]:


x = np.array([40,51,56,67,])
print(x)
print(type(x))


# In[13]:


#create 2D array
import numpy as np
a2 = np.array([[40,51],[56,67,]])
print(a2)
print(type(a2))
print(a2.shape)


# In[16]:


#create 3D array
import numpy as np
a3 = np.array([[40,51,65],[56,67,85]])
print(a3)
print(type(a3))
print(a3.shape)


# In[1]:


import numpy as np

a4 = np.array([[1, 'A', 9.8], [2, 'B', 10]])

print(a4)
print(type(a4))
print(a4.shape)



[40 51 56 67]
<class 'numpy.ndarray'>
[[40 51]
 [56 67]]
<class 'numpy.ndarray'>
(2, 2)
[[40 51 65]
 [56 67 85]]
<class 'numpy.ndarray'>
(2, 3)
[['1' 'A' '9.8']
 ['2' 'B' '10']]
<class 'numpy.ndarray'>
(2, 3)
